### ISSUE TITLE
cannot build or run demo

### ISSUE THREAD

**Issue by erik777** [nativescript-community/ble#252]
Same error whether I try to run or build it.  Was a clean clone.  Did a `tns install`.  I have no issue building or running apps I've created with NS.

$ tns run android
Searching for devices...
Starting Android emulator with image Pixel3a
Waiting for emulator device initialization...
Preparing project...
/home/user/dev2/git/nativescript-commuity/ble/demo/node_modules/webpack-cli/bin/cli.js:93
				throw err;
				^

```
Error: [copy-webpack-plugin] patterns must be an array
    at new CopyWebpackPlugin (/home/user/dev2/git/nativescript-commuity/ble/demo/node_modules/copy-webpack-plugin/dist/index.js:22:15)
    at module.exports (/home/user/dev2/git/nativescript-commuity/ble/demo/webpack.config.js:276:13)
    at handleFunction (/home/user/dev2/git/nativescript-commuity/ble/demo/node_modules/webpack-cli/bin/utils/prepareOptions.js:21:13)
    at prepareOptions (/home/user/dev2/git/nativescript-commuity/ble/demo/node_modules/webpack-cli/bin/utils/prepareOptions.js:9:5)
    at requireConfig (/home/user/dev2/git/nativescript-commuity/ble/demo/node_modules/webpack-cli/bin/utils/convert-argv.js:117:14)
    at /home/user/dev2/git/nativescript-commuity/ble/demo/node_modules/webpack-cli/bin/utils/convert-argv.js:123:17
    at Array.forEach (<anonymous>)
    at module.exports (/home/user/dev2/git/nativescript-commuity/ble/demo/node_modules/webpack-cli/bin/utils/convert-argv.js:121:15)
    at /home/user/dev2/git/nativescript-commuity/ble/demo/node_modules/webpack-cli/bin/cli.js:71:45
    at Object.parse (/home/user/dev2/git/nativescript-commuity/ble/demo/node_modules/yargs/yargs.js:576:18)
    at /home/user/dev2/git/nativescript-commuity/ble/demo/node_modules/webpack-cli/bin/cli.js:49:8
    at Object.<anonymous> (/home/user/dev2/git/nativescript-commuity/ble/demo/node_modules/webpack-cli/bin/cli.js:366:3)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/user/dev2/git/nativescript-commuity/ble/demo/node_modules/webpack/bin/webpack.js:156:2)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47
Executing webpack failed with exit code 1.
```

**Comment by farfromrefug** [comment]
@erik777 did you fix this? It has nothing to do with this plugin though and is webpack config issue ;)
